language: java

os: linux

# Need to select an older Ubuntu distribution that supports JDK7
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk11
  - openjdk14

# Workaround to using openjdk7 with Gradle due to security issue:
# https://github.com/gradle/gradle/issues/2421


  
script:
  - ./gradlew clean build javadoc

# Exclude the unsupported jdk on ppc64le travis.
